version: '3.8'

services:
  mongodb:
    image: mongo:7.0.12
    container_name: mongodb-cdc-test
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017" # 必需，供外部 Flink CDC 连接
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-config:/data/configdb
      - ./mongo-keyfile:/data/keyfile
    command: >
      --bind_ip_all 
      --replSet rs0 
      --oplogSize 128 
      --logappend 
      --logpath /var/log/mongodb/mongod.log 
      --keyFile /data/keyfile/mongodb-keyfile 
      --clusterAuthMode keyFile

  mongo-client:
    image: mongo:7.0.12
    container_name: mongo-client
    depends_on:
      mongodb:
        condition: service_started # 使用 started，因为带 keyFile 的 healthcheck 复杂
    volumes:
      - ./mongo-keyfile:/data/keyfile # 挂载 keyfile，以便 mongosh 能进行内部操作 (如果需要)
      - ./init-mongo.js:/scripts/init-mongo.js 
    command: >
      sh -c "
      sleep 30 &&
      echo 'Executing initialization script init-mongo.js...' &&
      mongosh --host mongodb --port 27017  -u admin -p password  --authenticationDatabase admin  --quiet /scripts/init-mongo.js &&
      echo 'Initialization script completed.' &&
      tail -f /dev/null
      "      
volumes:
  mongo-data:
  mongo-config:
  mongo-keyfile:
